export const ApplicantData = [
  {
    id: 1,
    name: "Hamish Marsh",
    jobId: 205,
    appliedTime: "18:56 PM",
    university: "University of Sri Jayewardenepura",
    image: "assets/Applicants/student01.jpg",
    location: "Nugegoda",
  },
  {
    id: 2,
    name: "Jhon doe",
    jobId: 206,
    appliedTime: "18:30 PM",
    university: "University of Colombo",
    image: "assets/Applicants/applicant.jpeg",
    location: "Kirulapana",
  },
  {
    id: 3,
    name: "Hamish Marsh",
    jobId: 205,
    appliedTime: "18:56 PM",
    university: "University of Sri Jayewardenepura",
    image: "assets/Applicants/student01.jpg",
    location: "Nugegoda",
  },
  {
    id: 4,
    name: "Jhon doe",
    jobId: 206,
    appliedTime: "18:30 PM",
    university: "University of Colombo",
    image: "assets/Applicants/applicant.jpeg",
    location: "Kirulapana",
  },
  {
    id: 5,
    name: "Hamish Marsh",
    jobId: 205,
    appliedTime: "18:56 PM",
    university: "University of Sri Jayewardenepura",
    image: "assets/Applicants/student01.jpg",
    location: "Nugegoda",
  },
  {
    id: 6,
    name: "Jhon doe",
    jobId: 206,
    appliedTime: "18:30 PM",
    university: "University of Colombo",
    image: "assets/Applicants/applicant.jpeg",
    location: "Kirulapana",
  },
  {
    id: 7,
    name: "Hamish Marsh",
    jobId: 205,
    appliedTime: "18:56 PM",
    university: "University of Sri Jayewardenepura",
    image: "assets/Applicants/student01.jpg",
    location: "Nugegoda",
  },
  {
    id: 8,
    name: "Jhon doe",
    jobId: 206,
    appliedTime: "18:30 PM",
    university: "University of Colombo",
    image: "assets/Applicants/applicant.jpeg",
    location: "Kirulapana",
  },
];
