export const postData = [
  {
    id: 1,
    image : "/assets/jobs/stockCounting.jpg",
    company: "MAS Holdings",
    title: "Stock Counting",
    location: "BOI Zone, Katunayake",
    startDate: "05/06/2023",
    endDate: "10/06/2023",
    start_time: "8.30 AM",
    end_time: "4.30 PM",
    payment: 2000,
    city: "Katunayake",
    discription:
      "The ACT Assessment was designed to measure knowledge and skills typically taught in high school that are important for successfully completing a college education. It contains tests from four general subject areas: English, Mathematics, Reading, Science Reasoning and Writing Skills. Questions regarding ACT credit should be referred to the Registrar's Office. Admission score requirements are according to whatever UMHB catalog is in effect at the time of admission. Information and instructions for registering for the ACT National Assessment and test dates can be found online at azct.org.",
  },
  {
    id: 2,
    image: "assets/jobs/designing.jpg",
    company: "Gray matter technologies",
    title: "Graphic Designing",
    location: "No 58, Nugegoda",
    startDate: "06/06/2023",
    endDate: "08/06/2023",
    start_time: "8.30 AM",
    end_time: "4.30 PM",
    payment: 5000,
    city: "Nugegoda",
    discription:
      "The purpose of the ACT Residual Assessment is for UMHB to obtain data on enrolled, admitted, or applicant students who were unable to take the ACT Assessment on a national test date. The ACT Residual Assessment is given by appointment only on scheduled dates.",
  },
  {
    id: 3,
    image: "assets/jobs/typing.jpg",
    company: "One zero Technologies",
    title: "Type Setting",
    location: "No 70, Panadura",
    startDate: "08/06/2023",
    endDate: "10/06/2023",
    start_time: "8.30 AM",
    end_time: "4.30 PM",
    payment: 5000,
    city: "Panadura",
    discription:
      "In some instances, a student may feel that he/she has sufficient knowledge in a certain subject area and does not wish to take the particular subject course. In such cases, the student may request to take a CLEP Examination in the particular subject area(s). To receive credit for the particular corresponding offered course, the student must obtain a score at or above the respective score listed on the Credit by Exam table.",
  },
  {
    id: 1,
    image : "/assets/jobs/stockCounting.jpg",
    company: "MAS Holdings",
    title: "Stock Counting",
    location: "BOI Zone, Katunayake",
    startDate: "05/06/2023",
    endDate: "10/06/2023",
    start_time: "8.30 AM",
    end_time: "4.30 PM",
    payment: 2000,
    city: "Katunayake",
    discription:
      "The ACT Assessment was designed to measure knowledge and skills typically taught in high school that are important for successfully completing a college education. It contains tests from four general subject areas: English, Mathematics, Reading, Science Reasoning and Writing Skills. Questions regarding ACT credit should be referred to the Registrar's Office. Admission score requirements are according to whatever UMHB catalog is in effect at the time of admission. Information and instructions for registering for the ACT National Assessment and test dates can be found online at azct.org.",
  },
  {
    id: 2,
    image: "assets/jobs/designing.jpg",
    company: "Gray matter technologies",
    title: "Graphic Designing",
    location: "No 58, Nugegoda",
    startDate: "06/06/2023",
    endDate: "08/06/2023",
    start_time: "8.30 AM",
    end_time: "4.30 PM",
    payment: 5000,
    city: "Nugegoda",
    discription:
      "The purpose of the ACT Residual Assessment is for UMHB to obtain data on enrolled, admitted, or applicant students who were unable to take the ACT Assessment on a national test date. The ACT Residual Assessment is given by appointment only on scheduled dates.",
  },
  {
    id: 3,
    image: "assets/jobs/typing.jpg",
    company: "One zero Technologies",
    title: "Type Setting",
    location: "No 70, Panadura",
    startDate: "08/06/2023",
    endDate: "10/06/2023",
    start_time: "8.30 AM",
    end_time: "4.30 PM",
    payment: 5000,
    city: "Panadura",
    discription:
      "In some instances, a student may feel that he/she has sufficient knowledge in a certain subject area and does not wish to take the particular subject course. In such cases, the student may request to take a CLEP Examination in the particular subject area(s). To receive credit for the particular corresponding offered course, the student must obtain a score at or above the respective score listed on the Credit by Exam table.",
  }
];
