export const jobData = [
  {
    id: 1,
    img: "assets/Jobs/stockCounting.jpg",
    title: "Stock Count",
    startTime: "01.00 PM",
    endTime: "05.00 PM",
    startDate: "24th April",
    endDate: "26th April",
    postedTime: "18:36 PM",
    postedDate: "23/04/2023",
    noOfApplicants: 26,
    company: "MAS Holdings",
  },
  {
    id: 2,
    img: "assets/Jobs/designing.jpg",
    title: "Post Designing",
    startTime: "02.00 PM",
    endTime: "08.00 PM",
    startDate: "25th April",
    endDate: "26th April",
    postedTime: "17:40 PM",
    postedDate: "24/04/2023",
    noOfApplicants: 31,
    company: "Hemas",
  },
  {
    id: 3,
    img: "assets/Jobs/typing.jpg",
    title: "Type Setting",
    startTime: "03.00 PM",
    endTime: "08.00 PM",
    startDate: "25th April",
    endDate: "26th April",
    postedTime: "17:40 PM",
    postedDate: "24/04/2023",
    noOfApplicants: 40,
    company: "MAS Holdings",
  },
];
